CPU_LITTLE_GOV="schedutil"
CPU_LITTLE_MIN="500000"
CPU_LITTLE_MAX="1800000"
CPU_BIG_GOV="schedutil"
CPU_BIG_MIN="700000"
CPU_BIG_MAX="2200000"
GPU_GOV="simple_ondemand"
GPU_MAX="800000000"
TOUCH_BOOST="1"

RATE_UP_US="2000"
RATE_DOWN_US="5000"
PEAK_FPS="120"
MIN_FPS="60"
STUNE_BOOST="1"

APP_RESTRICTION="allow"
LMK_MINFREE="18432,23040,27648,32256,55296,80640"
TIMER_SLACK="5000000"

TCP_CONG="cubic"
TCP_SYN_RETRIES="4"
TCP_SLOW_START="1"
FBT_ENABLE="1"
FBT_BOOST_TA="8"
FBT_RESCUE_PERCENT="65"
FBT_ULTRA_RESCUE="0"
FBT_FLOOR_BOUND="1000000"
FBT_CAM_BOOST="0"
UCLAMP_FG_MIN="20.00"
UCLAMP_BG_MAX="40.00"
