CPU_LITTLE_GOV="schedutil"
CPU_LITTLE_MIN="300000"
CPU_LITTLE_MAX="1000000"
CPU_BIG_GOV="schedutil"
CPU_BIG_MIN="300000"
CPU_BIG_MAX="1200000"
GPU_GOV="simple_ondemand"
GPU_MAX="450000000"
TOUCH_BOOST="0"

RATE_UP_US="5000"
RATE_DOWN_US="10000"
PEAK_FPS="60"
MIN_FPS="60"
STUNE_BOOST="0"

APP_RESTRICTION="ignore"
LMK_MINFREE="27648,32256,43008,55296,80640,115200"
TIMER_SLACK="100000000"

TCP_CONG="bbr"
TCP_SYN_RETRIES="2"
TCP_SLOW_START="1"
FBT_ENABLE="0"
FBT_BOOST_TA="0"
FBT_RESCUE_PERCENT="100"
FBT_ULTRA_RESCUE="0"
FBT_FLOOR_BOUND="300000"
FBT_CAM_BOOST="0"
UCLAMP_FG_MIN="0.00"
UCLAMP_BG_MAX="5.00"
