CPU_LITTLE_GOV="powersave"
CPU_LITTLE_MIN="480000"
CPU_LITTLE_MAX="1200000"
CPU_BIG_GOV="powersave"
CPU_BIG_MIN="480000"
CPU_BIG_MAX="1200000"
GPU_GOV="powersave"
GPU_MAX="450000000"
TOUCH_BOOST="0"

CPU_RATE="20000"
PEAK_FPS="60"
MIN_FPS="30"
STUNE_BOOST="0"

APP_RESTRICTION="ignore"
LMK_MINFREE="18432,23040,27648,32256,55296,80640"
TIMER_SLACK="50000000"

TCP_CONG="westwood"
TCP_SYN_RETRIES="6"
TCP_SLOW_START="1"
FPSGO_BOOST="0"
