MAX_DAILY_SOC=85
THERM_HI=380
THERM_LO=340
BLOAT_APPS="com.facebook.katana
com.facebook.appmanager
com.facebook.services
com.facebook.system
com.miui.analytics
com.google.android.feedback
com.google.android.printservice.recommendation
com.bikroy
org.xbet.client1
com.facebook.lite
com.facebook.orca
prod.app_ku9bdtf1.com
net.omobio.robisc
com.arena.banglalinkmela.app
com.konasl.nagad
com.bKash.customerapp
com.feralinteractive.laracroftgol_android
app.revanced.android.gms
com.mxtech.videoplayer.pro
io.metamask"
